#!/bin/bash

# Script to add Widget Extension target to Continuum project
# This opens Xcode with instructions

echo "🎯 Adding Widget Extension to Continuum..."
echo ""
echo "Opening Xcode project..."

# Open the project in Xcode
open continuum.xcodeproj

echo ""
echo "✨ Follow these quick steps in Xcode:"
echo ""
echo "1️⃣  In Xcode, click the blue 'continuum' project icon at the top of the left sidebar"
echo "2️⃣  Look at the 'TARGETS' section in the left panel"
echo "3️⃣  Click the '+' button at the bottom of the targets list"
echo "4️⃣  In the template chooser:"
echo "     • Platform: iOS"
echo "     • Filter: Type 'widget'"
echo "     • Select: 'Widget Extension'"
echo "     • Click 'Next'"
echo ""
echo "5️⃣  Configure the widget:"
echo "     • Product Name: continuumWidget"
echo "     • Team: (select your team)"
echo "     • Language: Swift"
echo "     • ❌ UNCHECK 'Include Configuration Intent'"
echo "     • Click 'Finish'"
echo ""
echo "6️⃣  Click 'Activate' when asked about the scheme"
echo ""
echo "7️⃣  Delete Xcode's generated files:"
echo "     • Delete the generated 'continuumWidget.swift'"
echo "     • Delete the generated 'Assets.xcassets'"
echo ""
echo "8️⃣  Add our custom widget files:"
echo "     • Right-click the 'continuumWidget' group in sidebar"
echo "     • Select 'Add Files to continuum...'"
echo "     • Navigate to the 'continuumWidget' folder"
echo "     • Select ALL files in it"
echo "     • ❌ UNCHECK 'Copy items if needed'"
echo "     • ✅ CHECK target 'continuumWidget' (NOT continuum)"
echo "     • Click 'Add'"
echo ""
echo "9️⃣  Share HabitDataManager:"
echo "     • Find 'Shared/HabitDataManager.swift' in sidebar"
echo "     • Select it"
echo "     • In right panel (File Inspector):"
echo "     • Under 'Target Membership', CHECK both:"
echo "       ✅ continuum"
echo "       ✅ continuumWidget"
echo ""
echo "🔟  Set up App Groups:"
echo "     • Select 'continuum' target"
echo "     • Go to 'Signing & Capabilities' tab"
echo "     • If no 'App Groups', click '+ Capability' → Add 'App Groups'"
echo "     • Click '+' under App Groups"
echo "     • Enter: group.com.orionlabs.continuum"
echo ""
echo "     • Select 'continuumWidget' target"
echo "     • Go to 'Signing & Capabilities' tab"
echo "     • Add 'App Groups' capability"
echo "     • Use SAME group: group.com.orionlabs.continuum"
echo ""
echo "1️⃣1️⃣  Build and Run:"
echo "     • Select 'continuum' scheme (top left)"
echo "     • Press ⌘R to build and run"
echo ""
echo "📱 After running, on your iPhone:"
echo "     • Long-press home screen → Enter jiggle mode"
echo "     • Tap '+' button (top-left)"
echo "     • Search 'Continuum'"
echo "     • You'll see your widgets! 🎉"
echo ""
echo "OR: Long-press the Continuum app icon → 'Edit Home Screen' → Tap '+'"
echo ""

# Wait for user confirmation
read -p "Press Enter when you've completed these steps..."

echo ""
echo "🏗️  Building project to verify..."
xcodebuild -scheme continuum -destination 'platform=iOS Simulator,name=iPhone 16 Pro' build > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo "✅ Build successful!"
    echo ""
    echo "🎉 Widget extension is ready!"
    echo "   Add widgets from your home screen!"
else
    echo "⚠️  Build had issues. Please check Xcode for errors."
    echo "   Common fixes:"
    echo "   • Make sure HabitDataManager is in both targets"
    echo "   • Verify App Groups match on both targets"
    echo "   • Clean build folder (⇧⌘K) and try again"
fi

echo ""
